<?php
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");
require("../config/config.php");

$block_muni_code = $_POST['block_muni_code'];
$personnel_export_query=$mysqli->prepare("SELECT personnel.personcd,personnel.officecd,personnel.officer_name,personnel.off_desg,personnel.adharno,personnel.present_addr1,personnel.present_addr2,personnel.perm_addr1,personnel.perm_addr2,personnel.dateofbirth,personnel.gender,personnel.scale,personnel.basic_pay,personnel.grade_pay,personnel.workingstatus,personnel.email,personnel.resi_no,personnel.mob_no,personnel.qualificationcd,personnel.languagecd,personnel.epic,personnel.acno,personnel.slno,personnel.partno,personnel.poststat,personnel.assembly_temp,personnel.assembly_off,personnel.assembly_perm,personnel.districtcd,personnel.subdivisioncd,personnel.bank_acc_no,personnel.bank_cd,personnel.branchname,personnel.branchcd,personnel.remarks,personnel.pgroup,personnel.upload_file,personnel.usercode,personnel.posted_date,personnel.f_cd,personnel.image,personnel.signature FROM personnel INNER JOIN office ON personnel.officecd = office.officecd WHERE office.blockormuni_cd = ? AND personnel.poststat != '' ORDER BY personnel.officecd, personnel.personcd") or die($mysqli->error);

$personnel_export_query->bind_param("s",$block_muni_code) or die($personnel_export_query->error);
$personnel_export_query->execute() or die($personnel_export_query->error);
$personnel_export_query->bind_result($personcd,$officecd,$officer_name,$off_desg,$adharno,$present_addr1,$present_addr2,$perm_addr1,$perm_addr2,$dateofbirth,$gender,$scale,$basic_pay,$grade_pay,$workingstatus,$email,$resi_no,$mob_no,$qualificationcd,$languagecd,$epic,$acno,$slno,$partno,$poststat,$assembly_temp,$assembly_off,$assembly_perm,$districtcd,$subdivisioncd,$bank_acc_no,$bank_cd,$branchname,$branchcd,$remarks,$pgroup,$upload_file,$usercode,$posted_date,$f_cd,$image,$signature) or die($personnel_export_query->error);

$return=array();
while($personnel_export_query->fetch())
{
    $return[]=array("personcd"=>mysqli_real_escape_string(htmlspecialchars($personcd)), "officecd"=>mysqli_real_escape_string(htmlspecialchars($officecd)), "officer_name"=>mysqli_real_escape_string(htmlspecialchars($officer_name)), "off_desg"=>mysqli_real_escape_string(htmlspecialchars($off_desg)), "adharno"=>mysqli_real_escape_string(htmlspecialchars($adharno)), "present_addr1"=>mysqli_real_escape_string(htmlspecialchars($present_addr1)), "present_addr2"=>mysqli_real_escape_string(htmlspecialchars($present_addr2)), "perm_addr1"=>mysqli_real_escape_string(htmlspecialchars($perm_addr1)), "perm_addr2"=>mysqli_real_escape_string(htmlspecialchars($perm_addr2)), "dateofbirth"=>mysqli_real_escape_string(htmlspecialchars($dateofbirth)), "gender"=>mysqli_real_escape_string(htmlspecialchars($gender)), "scale"=>mysqli_real_escape_string(htmlspecialchars($scale)), "basic_pay"=>mysqli_real_escape_string(htmlspecialchars($basic_pay)), "grade_pay"=>mysqli_real_escape_string(htmlspecialchars($grade_pay)), "workingstatus"=>mysqli_real_escape_string(htmlspecialchars($workingstatus)), "email"=>mysqli_real_escape_string(htmlspecialchars($email)), "resi_no"=>mysqli_real_escape_string(htmlspecialchars($resi_no)), "mob_no"=>mysqli_real_escape_string(htmlspecialchars($mob_no)), "qualificationcd"=>mysqli_real_escape_string(htmlspecialchars($qualificationcd)), "languagecd"=>mysqli_real_escape_string(htmlspecialchars($languagecd)), "epic"=>mysqli_real_escape_string(htmlspecialchars($epic)), "acno"=>mysqli_real_escape_string(htmlspecialchars($acno)), "slno"=>mysqli_real_escape_string(htmlspecialchars($slno)), "partno"=>mysqli_real_escape_string(htmlspecialchars($partno)), "poststat"=>mysqli_real_escape_string(htmlspecialchars($poststat)), "assembly_temp"=>mysqli_real_escape_string(htmlspecialchars($assembly_temp)), "assembly_temp"=>mysqli_real_escape_string(htmlspecialchars($assembly_off)), "assembly_perm"=>mysqli_real_escape_string(htmlspecialchars($assembly_perm)), "districtcd"=>mysqli_real_escape_string(htmlspecialchars($districtcd)), "subdivisioncd"=>mysqli_real_escape_string(htmlspecialchars($subdivisioncd)), "bank_acc_no"=>mysqli_real_escape_string(htmlspecialchars($bank_acc_no)), "bank_cd"=>mysqli_real_escape_string(htmlspecialchars($bank_cd)), "branchname"=>mysqli_real_escape_string(htmlspecialchars($branchname)), "branchcd"=>mysqli_real_escape_string(htmlspecialchars($branchcd)), "remarks"=>mysqli_real_escape_string(htmlspecialchars($remarks)), "pgroup"=>mysqli_real_escape_string(htmlspecialchars($pgroup)), "upload_file"=>mysqli_real_escape_string(htmlspecialchars($upload_file)), "usercode"=>mysqli_real_escape_string(htmlspecialchars($usercode)), "posted_date"=>mysqli_real_escape_string(htmlspecialchars($posted_date)), "f_cd"=>mysqli_real_escape_string(htmlspecialchars($f_cd)), "image"=>mysqli_real_escape_string(htmlspecialchars($image)), "signature"=>mysqli_real_escape_string(htmlspecialchars($signature)));
}	
echo json_encode($return);
?>
